#!/usr/bin/env bash
# =============================================================================
# changelog.sh — 自动从 git 历史生成 CHANGELOG.md
# 用法: bash changelog.sh [output_file]
# 默认输出: CHANGELOG.md
# 需求: git, bash
# =============================================================================

set -euo pipefail

OUTPUT="${1:-CHANGELOG.md}"
REPO_DIR="${2:-.}"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== CHANGELOG 生成器 ===${NC}"
echo "输出文件: $OUTPUT"
echo "仓库目录: $REPO_DIR"
echo ""

# 检查 git 仓库
if ! git -C "$REPO_DIR" rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}错误: 当前目录不是一个 git 仓库${NC}"
    exit 1
fi

cd "$REPO_DIR"

# 获取最后一个 tag，如果没有则用第一个 commit
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [ -z "$LAST_TAG" ]; then
    echo -e "${YELLOW}⚠ 没有找到 git tag，使用第一个 commit 作为起点${NC}"
    FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
    SINCE="$FIRST_COMMIT"
    TAG_LABEL="项目开始"
else
    SINCE="$LAST_TAG"
    TAG_LABEL="$LAST_TAG"
    echo -e "${GREEN}✅ 找到上次 tag: $LAST_TAG${NC}"
fi

echo "分析 commit 范围: $SINCE..HEAD"
echo ""

# 获取项目名称
PROJECT_NAME=$(basename "$(pwd)")

# 获取当前日期
NOW=$(date +"%Y-%m-%d")

# 分析 commit 消息
GIT_LOG=$(git log "$SINCE..HEAD" --format="%s|||%b|||%an|||%h" --no-merges 2>/dev/null || git log --format="%s|||%b|||%an|||%h" --no-merges)

if [ -z "$GIT_LOG" ]; then
    echo -e "${YELLOW}⚠ 没有找到新的 commit${NC}"
    exit 0
fi

# 分类
ADDED=""
FIXED=""
CHANGED=""
REMOVED=""
OTHER=""

while IFS= read -r line; do
    TITLE=$(echo "$line" | cut -d'|' -f1)
    BODY=$(echo "$line" | cut -d'|' -f2)
    AUTHOR=$(echo "$line" | cut -d'|' -f3)
    HASH=$(echo "$line" | cut -d'|' -f4)

    # 根据标题前缀分类
    TITLE_LOWER=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]')

    ENTRY="- $TITLE ([$HASH](https://github.com/placeholder/$PROJECT_NAME/commit/$HASH))"

    case "$TITLE_LOWER" in
        add*|feat*|feature*|new*|implement*|create*)
            ADDED="$ADDED\n$ENTRY"
            ;;
        fix*|bug*|patch*|hotfix*|correct*|resolve*)
            FIXED="$FIXED\n$ENTRY"
            ;;
        change*|update*|refactor*|improve*|optimize*|migrate*)
            CHANGED="$CHANGED\n$ENTRY"
            ;;
        remove*|delete*|deprecate*|drop*)
            REMOVED="$REMOVED\n$ENTRY"
            ;;
        *)
            OTHER="$OTHER\n$ENTRY"
            ;;
    esac
done <<< "$GIT_LOG"

# 生成 CHANGELOG.md
cat > "$OUTPUT" << CHANGELOG
# Changelog

## [$NOW] - $TAG_LABEL

CHANGELOG

# 添加分类
add_section() {
    local title="$1"
    local content="$2"
    if [ -n "$(echo "$content" | tr -d '\n ')" ]; then
        echo "" >> "$OUTPUT"
        echo "### $title" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
        echo -e "$content" | while read -r line; do
            [ -n "$line" ] && echo "$line" >> "$OUTPUT"
        done
    fi
}

if [ -n "$ADDED" ]; then
    echo "" >> "$OUTPUT"
    echo "### ✨ Added" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo -e "$ADDED" | while read -r line; do
        [ -n "$line" ] && echo "$line" >> "$OUTPUT"
    done
fi

if [ -n "$FIXED" ]; then
    echo "" >> "$OUTPUT"
    echo "### 🐛 Fixed" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo -e "$FIXED" | while read -r line; do
        [ -n "$line" ] && echo "$line" >> "$OUTPUT"
    done
fi

if [ -n "$CHANGED" ]; then
    echo "" >> "$OUTPUT"
    echo "### 🔄 Changed" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo -e "$CHANGED" | while read -r line; do
        [ -n "$line" ] && echo "$line" >> "$OUTPUT"
    done
fi

if [ -n "$REMOVED" ]; then
    echo "" >> "$OUTPUT"
    echo "### 🗑️ Removed" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo -e "$REMOVED" | while read -r line; do
        [ -n "$line" ] && echo "$line" >> "$OUTPUT"
    done
fi

if [ -n "$OTHER" ]; then
    echo "" >> "$OUTPUT"
    echo "### 📋 Other" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo -e "$OTHER" | while read -r line; do
        [ -n "$line" ] && echo "$line" >> "$OUTPUT"
    done
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "_Generated by [changelog.sh](https://github.com/claude-builders-bounty/claude-builders-bounty)_" >> "$OUTPUT"

echo -e "${GREEN}✅ CHANGELOG.md 已生成: $(pwd)/$OUTPUT${NC}"
echo -e "   总 commit: $(echo "$GIT_LOG" | grep -c "^" || echo "0")"
echo ""
echo "📋 分类统计:"
[ -n "$ADDED" ] && echo "   ✨ Added:   $(echo -e "$ADDED" | grep -c "^  - " || echo "0")"
[ -n "$FIXED" ] && echo "   🐛 Fixed:   $(echo -e "$FIXED" | grep -c "^  - " || echo "0")"
[ -n "$CHANGED" ] && echo "   🔄 Changed: $(echo -e "$CHANGED" | grep -c "^  - " || echo "0")"
[ -n "$REMOVED" ] && echo "   🗑️ Removed: $(echo -e "$REMOVED" | grep -c "^  - " || echo "0")"
[ -n "$OTHER" ] && echo "   📋 Other:   $(echo -e "$OTHER" | grep -c "^  - " || echo "0")"
